# Generated by Django 2.2 on 2020-06-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200531_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'animal'), ('C', 'crop'), ('S', 'service')], max_length=1),
        ),
    ]
