# Generated by Django 2.2 on 2020-06-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200601_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'animal'), ('C', 'crop'), ('S', 'services')], max_length=1),
        ),
    ]
